###
POST http://localhost:6060/api/movies
Content-Type: application/json

{
    "pageSize": 1,
    "filter": {
        "isFiltered": true,
        "searchText": "42nd Street"
    }
}


###
GET http://localhost:6060/api/movies/573a1391f29313caabcd8cef


###
DELETE http://localhost:6060/api/movies/573a1390f29313caabcd4135


###
PUT http://localhost:6060/api/movies/573a1390f29313caabcd50e5
Content-Type: application/json

{ 
    "directors": ["Suhbat"]
}

###
POST http://localhost:6060/api/movies
Content-Type: application/json

{
    "title": "Mongol humuus alt",
    "rating": 9.9,
    "directors": ["amaraa" , "tom amaraa"]
}

### 
POST http://localhost:6060/api/moviesfilter
Content-Type: application/json

{
    "pageSize": 1,
    "filter": {
        "searchText": "as",
        "rated": 2
    }
}
